### ISSUE TITLE
update madrob

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/eurobench_protocol#22]
The PI list has been updated. 

* The eurobench repo needs to be updated
* The docker image has to be regenerated
* the excel file has to be updated
* the yaml file has to be updated.

**Comment by aremazeilles** [comment]
ping @Enri2077 @alfonsotecnalia 

Most of the action are on Alfonso and my side, but if you can start updating the excel sheet @Enri2077 , that could help us.

**Comment by Enri2077** [comment]
I'll do the excel sheet.
Could you clarify what "Missing: indication on data collected files." means under madrob in the README of this repo?
Thanks

**Comment by Enri2077** [comment]
https://github.com/eurobench/eurobench_protocol/pull/23

**Comment by aremazeilles** [comment]
To generate the new release, could you confirm me the changes you did? I noted the following:

* corrected smoothness_of_door_actuation and removed door_handle_smoothnes

Does it reflect the changes you did?

**Comment by aremazeilles** [comment]
About _Missing: indication on data collected files_ :

It would be great having some indications of how are structured  the data collected (filenames mainly, if data is already in pre-processed format). That would help us verifying whether our PI Manager can handle it. or whether we have to add some file renaming processing before uploading data into the Eurobench server.

I am not sure of where that information should be indicated although, but that would be great to check it.

**Comment by aremazeilles** [comment]
_The eurobench repo needs to be updated_ : done
By the way, the way I do it was by  creating  PR from your repo to my fork. So it could be an efficient way to do it in the future, and make sure this way we are informed about code changes.

**Comment by Enri2077** [comment]
> To generate the new release, could you confirm me the changes you did? I noted the following:
> 
> * corrected smoothness_of_door_actuation and removed door_handle_smoothnes
> 
> Does it reflect the changes you did?

Yes, but additionally in https://github.com/madrob-beast/madrob_beast_pi/commit/9d7ab002146fb402bfb8b05279adcdbdb97f5238 I also changed the implementation of the PIs execution time and passage time.
All other PI implementations has changed but in a way that does not change their results.

**Comment by Enri2077** [comment]
> About _Missing: indication on data collected files_ :
> 
> It would be great having some indications of how are structured the data collected (filenames mainly, if data is already in pre-processed format). That would help us verifying whether our PI Manager can handle it. or whether we have to add some file renaming processing before uploading data into the Eurobench server.
> 
> I am not sure of where that information should be indicated although, but that would be great to check it.

I'll specify this in the README of the madrob_beast_pi somewhere. Although in our case theresn't much to say since the preprocessed data is generated directly and does not need renaming (apart from taking every file from each run directory and copying them in a folder before uploading).

**Comment by Enri2077** [comment]
Added information about preprocessed data format https://github.com/madrob-beast/madrob_beast_pi/commit/5ed98df4fe6e767e7ba6966774241e7f4d6fbb64
