### ISSUE TITLE
beat source repositories are not sync

### ISSUE THREAD

**Issue by alfonsotecnalia** [eurobench/eurobench_protocol#26]
The one in this [link](https://github.com/aremazeilles/beat_routine) is more advanced than the one that generates and uploads the docker image to docker_hub.

**Comment by aremazeilles** [comment]
You are right.

The project owner should inform us that some updates have been done, so that we can brgin them to the Eurobench repo, and then create a release of it. As I "own" the base repo, well I forgot to do it.

Process under progress, letting the CI t confirm integration is ok.

**Comment by aremazeilles** [comment]
I think this is solved now. https://hub.docker.com/r/eurobenchtest/pi_beat

**Comment by aremazeilles** [comment]
Can this be closed?

**Comment by aremazeilles** [comment]
ping

**Comment by aremazeilles** [comment]
Now it would get outdated, once we merge https://github.com/aremazeilles/beat_routine/pull/48 
Could you comment there if this change is ok with you?

**Comment by alfonsotecnalia** [comment]
I have already merged it.

**Comment by aremazeilles** [comment]
Now I think I have to update the _eurobench_ version, and push a new release. Will do asap

**Comment by aremazeilles** [comment]
I just uploaded the new version to v0.1.1
Actually, I see from https://hub.docker.com/repository/docker/eurobenchtest/pi_beat that it was just uploaded by someone. Is it you?

Could you close the issue once the updated docker image is effectively loaded?

Thanks

**Comment by alfonsotecnalia** [comment]
I do not know. If I have done it, I have not done it on purpose. Maybe it is part of the jobs.

**Comment by alfonsotecnalia** [comment]
Tested and updated to eurobench platform. protocol statushas been updated in https://github.com/eurobench/eurobench_protocol
