### ISSUE TITLE
insert sbs_ergonomic

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/eurobench_protocol#35]
Step by step should have several protocols, but I already filled one, [sbs_biomechanics](https://github.com/eurobench/eurobench_protocol/blob/main/data/stepByStep.yaml)

Would it be possible to upload this one?

**Comment by alfonsotecnalia** [comment]
A user for step_by_step should be created before but it is not possible now because the web is down.

**Comment by alfonsotecnalia** [comment]
Protocols inserted.  `duration` reduced to fit 100 characters. `estimated_experiment_duration` field in `protocol` table should be extended to 200. website (chrome, edge) is not showing them in a correct way (or I do not see them)

**Comment by alfonsotecnalia** [comment]
Done. Manual and image should be updated the next time the script in S3 is updated.

**Comment by alfonsotecnalia** [comment]
Issue can be closed

**Comment by aremazeilles** [comment]
I would wait for the manual to be uploaded before closing it.
Actually, I see the protocol "Walking on stairs: Local Perceived Pressure Questionnaire" twice: https://15.237.22.1/protocols/info/63 and https://15.237.22.1/protocols/info/64 

Is it normal?

**Comment by alfonsotecnalia** [comment]
I forgot to comment it. In the yaml the name, readable_name or description (I do not remember) is repeated. One of them is a combination of two previous protocols.

**Comment by aremazeilles** [comment]
OK, I will chck that later, when I will have a bit of time (not now)

I should also update the readme page, with the status of the Step by step protocols.

**Comment by alfonsotecnalia** [comment]
manual has been uploaded
