### ISSUE TITLE
insert uncomplete sbs protocols

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/eurobench_protocol#36]
Aside #35 (which as an algo inserted), I also inserted the other protocols related to Step by step.
As I am still missing information about the algoritms and PI, I just inserted the protocol description.

Is it possible to insert these additional protocols as is? Or should we add a section on the PI algo even if empty?

This may affect the resolution of #35, as it is in the same file, and same branch. Sorry for that...

**Comment by alfonsotecnalia** [comment]
All the stuff done in #35. This issue can be closed.
