### ISSUE TITLE
[RRD] upload pdf

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/eurobench_protocol#41]

**Comment by alfonsotecnalia** [comment]
Do we have it? I do not see it in this repo

**Comment by alfonsotecnalia** [comment]
Do we have it? I do not see it in this repo

**Comment by aremazeilles** [comment]
I just uploaded it. Here it is: https://github.com/eurobench/eurobench_protocol/tree/main/data/rrd/manual

**Comment by alfonsotecnalia** [comment]
Uploaded to the instance
