### ISSUE TITLE
Pure matlab code

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/eurobench_protocol#49]
@alfonsotecnalia do you think you would have the time to handle them, or should I ?

I think the solution for generating the doker imae works, we would have to upload it manually. 
Then on one of the two, there was 2 algorithm to handle. If we can leave with 2 different docker images, then that would be the faster solution.

While writting this, maybe you do not have the right to upload docker image to the docker hub. So maybe I should do it then?
Any comment welcome

**Comment by alfonsotecnalia** [comment]
I could do some tests with the one with the two algorithms.
However, as you have mentioned, I do not have the permissions to upload them to docker hub

**Comment by aremazeilles** [comment]
OK, let me resume the situation then

**Comment by aremazeilles** [comment]
I am uploading the benchbalance image to Docker, but it is very slow. 
When done, I'll tell you so that you can check if the image can be pulled and used, ok?

Experience has 2 entry points. At short term, I would propose to generate two docker images. If we have time, we can check how we can combine the two, but this may not be a priority. I'll wait to test benchbalance before handling experience. 

Does it sounds like a good plan to you?

**Comment by alfonsotecnalia** [comment]
ok. Let me know when benchbalance is ready to be downloaded.

**Comment by aremazeilles** [comment]
It took ages!!!!
Docker image: https://hub.docker.com/repository/docker/eurobenchtest/pi_benchbalance

Indications of use in the readme of branch [docker](https://github.com/aremazeilles/PI_BenchBalance/tree/docker#docker-image-generation-and-usaged)

**Comment by alfonsotecnalia** [comment]
It seems that matlab docker images does not have an entry point. At this momment pi_manager gives an error if this field is empty. I will change it.

**Comment by alfonsotecnalia** [comment]
The tag of this docker image is latest. The tags of the rest of the docker images have the following format vx.y.z.

**Comment by aremazeilles** [comment]
ok. Could you try lqunching it directly on your machine?

**Comment by aremazeilles** [comment]
I had to set the name manually. I should be able to change it to v0.0.0 
Do you want me to do so?

**Comment by alfonsotecnalia** [comment]
It is working with the provided instruction in the README

**Comment by alfonsotecnalia** [comment]
It is not necessary to change the tag.
I have already adapted the pi_manager to accept empty entries. Matlab entries should be specified following this format: ";jointAngles.csv;conditon.yaml".
The yaml in eurobench protocol need to be adapted: entry point and associated pi (the name of the pi is with underscore and the generated files are without it). I will change them.

**Comment by aremazeilles** [comment]
ok, I´ll prepare space for experience, as the upload process took something like ... 2 hours ...

**Comment by alfonsotecnalia** [comment]
benchbalance uploaded.

The PiManager in Eurobench instance need to be updated. I will comment it to Adrian

**Comment by aremazeilles** [comment]
I assume this can be closed, right?
